### ISSUE TITLE
To-Do for CGI

### ISSUE THREAD

**Issue by loudapet** [loudapet/42webserv#66]
- [x] `cgi_path test1.cgi;` > rewrite to `cgi on/off` @andreaulicna 
  - [x] return 404(?) when URL doesn't end in supported extensions, but is located on CGI path @loudapet 
- [x] `/some/cgi/url/test.py/additional/path/info` needs to be parsed for PATH_INFO even when there are multiple extensions supported (/test/test1.php/test.cgi) @loudapet 
  - [x] parse on first valid extension, consider supporting difference between a folder  and a file @loudapet
  - [x] needs to check if the file is excecutable (or 403 if not) @loudapet 
- [x] process ENV for CGI (#62) @okraus42 
- [x] process larger files in CGI (#65) @okraus42 
- [x] CGI read/write through select (#61) @okraus42 
  - [x] add fdIsSetWrite and fdIsSetRead "getters" in ServerMaster @andreaulicna 
  - [x] add fds of pipes to client response @okraus42

**Comment by loudapet** [comment]
Refer to f55c2605b09e30dd3becd2ba153ec1dbd3554fac for changes regarding PATH_INFO and related parsing issues.
Currently hardcoded values for CGI path, will update once config parser supports CGI flag

**Comment by andreaulicna** [comment]
If ever needed - checks for cgi relative path existing, being accessible and executable:
```
const std::string	&relativePath = this->_locations[i].getRelativeCgiPath();
if (access(relativePath.c_str(), F_OK) < 0)
  throw(std::runtime_error("Config parser: CGI relative path '" + relativePath + "' is invalid."));
if (access(relativePath.c_str(), R_OK) < 0)
  throw(std::runtime_error("Config parser: CGI at '" + relativePath + "' is not accessible."));
if (access(relativePath.c_str(), X_OK) < 0)
  throw(std::runtime_error("Config parser: CGI at '" + relativePath + "' is not executable."))
```

**Comment by andreaulicna** [comment]
Refer to 78d5cc10bd1428b775a3f414762c895c4e8a2166 for changes regarding the cgi directive in the config and fdIsSetRead/Write "getters".
Currently hardcoded values for CGI {relative) path, @okraus42 should update as apropriate.

**Comment by okraus42** [comment]
CGI now goes through proper loops to handle bigger files and go through select to be non-blocking (refer to 30ca0d75933809ec5d5bf199a04e19e1be5616b4 )

**Comment by okraus42** [comment]
#75 Should be working properly.
